### ISSUE TITLE
Details about the annotation process

### ISSUE THREAD

**Issue by Richar-Du** [mutonix/Vript#1]
Thanks for your awesome work! I have some questions about the annotations process:
1. How many frames do you give to GPT-4V for video captions of each scene? And how to use the text information (e.g., subtitle, script) in this process.
2. How to divide each video into different scene clips?

Thanks for your work again, could you please describe more details of the annotations process?

**Comment by mutonix** [comment]
We have updated the annotation details to readme. You can check https://github.com/mutonix/Vript#annotation-details.

**Comment by Richar-Du** [comment]
Thank you for your reply!

Another question is: How do I use the Vript-RR benchmark? I noticed there are 'video_id' and 'clip_id' keys in the annotation. Which one should be used as the input for the model, the video or the clip? If I input the whole video to the model, will the question be ambiguous, since the question is about a specific scene?

**Comment by Richar-Du** [comment]
Got it! Thanks for your quick reply :)

**Comment by fiaz-ali** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
thesw4rm, @teguhmurdianto, @laurin-kraemer, @sebastian-trinito, @eabasguliyev, @Jev121, @jonghwaC, @xiaohangt, @ishu-codes, @eliwheaton, @minhpn76, @pawelmiklas, @saurabhmehta1601, @GerwinSchwarzz, @talhayavcin, @B7ackCa7, @likhitkalla, @huaguihai, @MarcoCavi, @yadukpb, @shogi880, @paulgid, @Manjunaths9731, @ahmedrabea30, @DaNyNaNd, @Ckrielle, @AloneAtWar, @MichelKaliMike, @hazlytech, @Phoenix009, @fountainhead-gq, @2997ms, @manishpandoh2946, @Mobinshahidi, @vidcornd, @mzizmfz, @ViciousValentine, @windfoxx, @lavanic99, @rusov3, @zzhsec, @code-pony1, @gugki, @sudolink, @shizhaojingszj, @Gregoryann, @cdchap, @acignetti, @Mawlong, @wwnbbd
