### ISSUE TITLE
Model Release & Demo 

### ISSUE THREAD

**Issue by plmsmile** [mutonix/Vript#5]
Thanks for sharing of the great work. I have 2 questions~ 
1. Will you plan to release the model weight?
2. The vriptor demo not work now and only empty show in the page. https://huggingface.co/spaces/Mutonix/Vriptor-stllm

**Comment by mutonix** [comment]
Thank you for your interest in our work.
1. We will release the mode weight in a few days.
2. We check the page of the vriptor demo and it is working fine. You may need to wait a few seconds for the page to load.

**Comment by mutonix** [comment]
We have released the model weight, please check [here](https://github.com/mutonix/Vript/tree/main/vriptor).
