### ISSUE TITLE
run the demo in A100 80G: CUDA out of memory

### ISSUE THREAD

**Issue by LAW1223** [mutonix/Vript#6]

**Comment by mutonix** [comment]
Can you offer more information about how you get OOM? You can constrain the output length of the model to avoid outputting too long text, which may lead to OOM.

**Comment by LAW1223** [comment]
Thanks a lot.
The config of generation is:
`chat.upload_video(video, chat_state, img_list, 64, text=prompt)
chat.ask("###Human: " + prompt + " ###Assistant: ", chat_state)
llm_message = chat.answer(conv=chat_state,
                img_list=img_list,
                num_beams=3,
                do_sample=True,
                max_new_tokens=2048,
                top_p=0.9,
                repetition_penalty=1.5,
                max_length=8192)[0]`
`python demo.py \
    --video-path /data/captioning/Vript/emoji_1.mp4 \
    --cfg-path config/vriptor_stllm_stage2.yaml \
    --gpu-id 0 \
    --ckpt-path /mnt/models/Vriptor-STLLM`
    
    In the config/vriptor_stllm_stage2.yaml, I changed the   q_former_model to my path: '/mnt/captioning/Vript/instruct_blip_vicuna7b_trimmed.pth'

**Comment by mutonix** [comment]
You can reduce the `max_length` from 8192 to 1024.

**Comment by LAW1223** [comment]
When I changed it:
IndexError: index 0 is out of bounds for dimension 0 with size 0

**Comment by mutonix** [comment]
Maybe 1024 is too short for video input. Please try to set the `max_length` to 4096 or set `max_new_tokens=1024` instead of setting `max_length`.
