### ISSUE TITLE
3个数据集的区别

### ISSUE THREAD

**Issue by yuanliping** [mutonix/Vript#9]
您好，请问Mutonix/Vript、Mutonix/Vript_Chinese、Mutonix/Vript_Multilingual这3个数据集的原视频clip有重合的嘛？

**Comment by mutonix** [comment]
没有 第一个是yt 第二个cn是抖音 第三个multilingual是b站
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年10月31日 10:46 收件人 ***@***.***> 抄送至 ***@***.***> 主题 [mutonix/Vript] 3个数据集的区别 (Issue #9) 
您好，请问Mutonix/Vript、Mutonix/Vript_Chinese、Mutonix/Vript_Multilingual这3个数据集的原视频clip有重合的嘛？
